project_id: "574887"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
# Setting export_languages here doesn't seem to work -- we get all languages.
# So, instead, we're setting the languages we want in the cli command; see package.json
#export_languages: ["fr", "es", "pt", "hi"]
files: [
    {
      # Using *.* because we want .md files and images.
      "source": /docs/*.*,
      "translation": /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_file_name%,
    },
    {
      # Using *.* because we want .md files and images.
      "source": /docs/Training-manual/**/*.*,
      "translation": /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/Training-manual/**/%original_file_name%,

    # Using *.* because we want .md files and images.
      "source": /docs/Administrator's Manual/**/*.*,
      "translation": /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/Administrator's-Manual/**/%original_file_name%,

      # "skip_untranslated_files": true,

      # We don't want _category_.json files because those get localized via current.json.
      "ignore": ["**/_category_.json"],
    },
    {
      "source": /i18n/en/docusaurus-plugin-content-docs/current.json,
      "translation": /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current.json,
    },
    {
      "source": /i18n/en/docusaurus-theme-classic/navbar.json,
      "translation": /i18n/%two_letters_code%/docusaurus-theme-classic/navbar.json,
    },
  ]
