// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

// prism-react-renderer 2.x moved the themes to a named export on the package root;
// the old "prism-react-renderer/themes/github" subpath no longer resolves.
const { themes: prismThemes } = require("prism-react-renderer");
const lightCodeTheme = prismThemes.github;
const darkCodeTheme = prismThemes.dracula;

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Paratext Manual",
  tagline: "",
  url: "https://manual.paratext.org",
  baseUrl: "/",
  onBrokenLinks: "warn",
  // New in Docusaurus v3. Defaults to "warn"; set explicitly so it can't start
  // failing the build on a minor upgrade. docu-notion links headings by Notion
  // block id, so an anchor dies whenever a heading block is deleted in Notion.
  onBrokenAnchors: "warn",
  // Duplicate routes cause the next/prev buttons to loop
  // which causes the pdf creation to loop forever.
  onDuplicateRoutes: "throw",
  favicon: "img/favicon.ico",

  markdown: {
    // Docusaurus 3.9 moved onBrokenMarkdownLinks here from the top level.
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
    // These are ON by default in Docusaurus 3, but we set them EXPLICITLY because
    // Docusaurus 4 flips the default off (see the `future.v4.mdx1CompatDisabledByDefault`
    // flag). The option itself is not being removed -- v4 resolves each flag with
    // `??=`, so an explicit value keeps winning. Setting them here means a v4 upgrade
    // won't silently change how our content renders.
    //
    // We rely on all three because our content is intentionally in the Docusaurus v2
    // markdown forms:
    //   - `{#id}` heading ids     -- `yarn pull` passes --docusaurus-v2 (see package.json),
    //                                and the Crowdin translations in i18n/ match.
    //   - `:::caution`            -- still a valid v3 keyword, and a bare one gets a
    //                                localized title from Docusaurus' own translations
    //                                (fr "attention"), which an explicit label would lose.
    //   - `:::info Some Title`    -- the v2 space-separated admonition title. ~17 of these
    //                                are hand-typed as literal text inside Notion, so they
    //                                regenerate on every pull and can only be fixed there.
    //
    // Docusaurus does this conversion at build time in @docusaurus/mdx-loader's
    // preprocessContent (escapeMarkdownHeadingIds + admonitionTitleToDirectiveLabel).
    // Don't hand-roll it -- see README for why.
    mdx1Compat: {
      comments: true,
      admonitions: true,
      headingIds: true,
    },
  },

  organizationName: "sillsdev", // Usually your GitHub org/user name.
  projectName: "paratext-manual", // Usually your repo name.
  deploymentBranch: "gh-pages",

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/", // Serve the docs at the site's root
          sidebarPath: undefined, //  `undefined` to create a fully autogenerated sidebar.
        },
        blog: false,
        theme: {
          customCss: [
            require.resolve("./css/docu-notion-styles.css"),
            require.resolve("./src/css/custom.css"),
          ],
        },
        sitemap: {
          // https://www.sitemaps.org/protocol.html#xmlTagDefinitions
          changefreq: "weekly",
          priority: 0.5,
          ignorePatterns: [],
        },
      }),
    ],
  ],
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr", "es", "pt", "hi"],
    localeConfigs: {
      en: {
        label: "English",
        direction: "ltr",
        htmlLang: "en-US",
        calendar: "gregory",
      },
      fr: {
        label: "français",
        direction: "ltr",
        htmlLang: "fr",
        calendar: "gregory",
      },
      es: {
        label: "español",
        direction: "ltr",
        htmlLang: "es",
        calendar: "gregory",
      },
    },
  },
  themes: [
    // ... Your other themes.
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        // ... Your options.
        // `hashed` is recommended as long-term-cache of index file is possible.
        hashed: true,
        language: ["en", "fr", "es", "pt"],
        indexBlog: false,
        indexPages: true,
        docsRouteBasePath: "/",
      },
    ],
  ],
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      metadata: [
        {
          name: "keywords",
          content: "Paratext, documentation, help, manual, training",
        },
      ],
      navbar: {
        title: "Paratext Manual",
        items: [
          {
            type: "localeDropdown",
            position: "right",
          },
        ],
      },

      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
