name: Generate PDF
on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language to generate PDF for'
        required: true
        default: 'en'
        type: string
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Generate PDF
        run: yarn make-pdf ${{ inputs.language }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
