name: Generate PDF
on:
  workflow_dispatch:
    inputs:
      language:
        description: "Language to generate PDF for"
        required: true
        default: "en"
        type: string
jobs:
  release:
    name: Generate PDF for ${{ inputs.language }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Install Devanagari font if needed
        if: ${{ inputs.language == 'hi' }}
        run: |
          sudo git clone --depth 1 --filter=blob:none --no-checkout https://github.com/google/fonts.git
          cd fonts
          sudo git checkout main -- ofl/notosansdevanagari
          sudo mkdir -p /usr/share/fonts/notosansdevanagari
          sudo cp ofl/notosansdevanagari/*.ttf /usr/share/fonts/notosansdevanagari/
          sudo fc-cache -fv
      - name: Disable AppArmor
        # Ubuntu >= 23 has AppArmor enabled by default, which breaks Puppeteer.
        # See https://github.com/puppeteer/puppeteer/issues/12818 "No usable sandbox!"
        # this is taken from the solution used in Puppeteer's own CI: https://github.com/puppeteer/puppeteer/pull/13196
        # The alternative is to pin Ubuntu 22 or to use aa-exec to disable AppArmor for commands that need Puppeteer.
        # This is also suggested by Chromium https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash
      - name: Generate PDF
        run: yarn make-pdf ${{ inputs.language }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # In this workflow, we want to keep the existing files because all we want to do is add the PDF we just generated.
          # That way we don't have to build the docusaurus site again.
          keep_files: true
