name: Generate PDF
on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language to generate PDF for'
        required: true
        default: 'en'
        type: string
jobs:
  release:
    name: Generate PDF for ${{ inputs.language }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Install Devanagari font if needed    
        if: ${{ inputs.language == 'hi' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-core
      - name: Generate PDF
        run: yarn make-pdf ${{ inputs.language }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # In this workflow, we want to keep the existing files because all we want to do is add the PDF we just generated.
          # That way we don't have to build the docusaurus site again.
          keep_files: true