name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Pull from Notion
        env:
          PARATEXT_NOTION_INTEGRATION_TOKEN: ${{ secrets.PARATEXT_NOTION_INTEGRATION_TOKEN }}
          PARATEXT_NOTION_ROOT_PAGE: ${{ secrets.PARATEXT_NOTION_ROOT_PAGE }}
        run: yarn pull
      - name: Commit New Source Material
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GHAction - Commit content changes pulled from notion
      - name: Crowdin
        run: yarn crowdin:sync
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: Commit New Translations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GHAction - Commit incoming translations from Crowdin
      - name: Build Docusaurus instance for github pages branch
        run: yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
